name: BlockParty
version: ${project.parent.version}
description: Unofficial patched-armageddon BlockParty Plugin
main: de.leonkoth.blockparty.Main
authors: [Kawlxz, Leon167, pauhull]
website: https://github.com/Leon167/BlockParty-2.0/
softdepend: [Multiverse-Core, ReWorld, MCJukebox, NoteBlockAPI, TimoCloud]

commands:
  blockparty:
    aliases: [bp, bparty]
    description: Get information on how to use this Plugin
    usage: /blockparty - to get more information
    permission: blockparty.command

permissions:
  blockparty.command:
    default: true
    description: Access to the main command.

api-version: 1.16